import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Top from "@/components/includes/top";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";
import Header from "@/components/includes/header";
import Footer from "@/components/includes/footer";
import NoScript from "@/components/includes/noscript";

const iranSansDs = localFont({
  src: "./iransansdnweb.woff2",
  variable: "--iranSansDs",
});

export const metadata: Metadata = {
  title: {
    template: "%s | اسم سایت",
    default: "اسم سایت",
  },
  description: "Generated by create next app",
  keywords: ["Next"],
  robots:
    "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  openGraph: {
    title: "عنوان مقاله یا سایت",
    type: "article", // اگر صفحه اصلی سایت بود باید website بشه
    url: "آدرس سایت اگر وبلاگ بود آدرس وبلاگ",
    images: "آدرس عکس تامنیل یا آدرس عکس اصلی سایت",
    siteName: "اسم سایت",
    locale: "fa_IR",
    description: "توضیحات",
  },
  twitter: {
    title: "example.ssd",
    description: "example",
    images: "example",
    card: "summary_large_image",
    site: "@example.ir",
    creator: "@example.ir",
  },
  verification: {
    google: "",
  },
  alternates: { canonical: "آدرس سایت اگر وبلاگ بود آدرس وبلاگ" },
  formatDetection: { telephone: false },
  appleWebApp: { capable: true },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR">
      <meta name="news_keywords" content="کلمات مهم" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
      <meta
        name="googlebot"
        content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
      />
      <meta name="theme-color" content="#f8f9fa" />
      <meta name="msapplication-navbutton-color" content="#f8f9fa" />
      <meta property="og:image:width" content="900" />
      <meta property="og:image:height" content="900" />
      <meta property="og:image:type" content="image/jpeg" />
      <body className={`d-flex flex-column vh-100 ${iranSansDs.variable}`}>
        <Header />
        <main>{children}</main>
        <Top />
        <Footer />
        <NoScript />
        <ToastContainer rtl={true} />
        <NextTopLoader color="#0d6efd" showSpinner={false} />
      </body>
    </html>
  );
}
