import { Metadata } from "next";
import Single from "@/components/blog/single";

export const metadata: Metadata = {
  title: "mmd",
  description: "Generated by create next app",
  keywords: ["Next"],
  robots:
    "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  twitter: {
    title: "example.mmd",
    description: "example",
    images: "example",
    card: "summary_large_image",
    site: "@example.ir",
    creator: "@example.ir",
  },
};

export default function blog() {
  return <Single />;
}
